### ISSUE TITLE
DeltaUtah

### ISSUE THREAD

**Issue by josiesajbel** [UW-Macrostrat/burwell-processing#1]
## Info

**Name:** DeltaUtah

**Source URL:** http://geology.utah.gov/map-pub/maps/gis/#tab-id-1

**Estimated scale:** Large

**Lithology field:** Lithology

**Time field:** AGE

**Stratigraphy name field:** UNITNAME

**Description field:** Lithology

**Comments field:** 

**Comments:** 
## Todo:
- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Match
- [x] Roll tiles
- [ ] Import lines
