### ISSUE TITLE
Denver, Colorado

### ISSUE THREAD

**Issue by ItoErika** [UW-Macrostrat/burwell-processing#112]
## Info

**Name:**
Denver, Colorado

**Source URL:**
http://pubs.usgs.gov/imap/i-856-h/

**Estimated scale:**
medium?

**Number of bedrock polygons:**
6,136

**Lithology field:**

**Time field:**
age

**Stratigraphy name field:**
name

**Description field:**
description

**Comments field:**

**Comments:**
## Todo:
- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Match
- [ ] Process and import lines
- [x] Roll tiles
