### ISSUE TITLE
Southern Texas and Mexico

### ISSUE THREAD

**Issue by ItoErika** [UW-Macrostrat/burwell-processing#117]
## Info

**Name:**
Southernmost Texas, United States, and parts of Tamaulipas and Nuevo Leon, Mexico

**Source URL:**
http://pubs.usgs.gov/of/2005/1409/

**Estimated scale:**
medium?

**Number of bedrock polygons:**
4,680

**Lithology field:**

**Time field:**
age

**Stratigraphy name field:**
name

**Description field:**
description

**Comments field:**

**Comments:**
## Todo:
- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Match
- [ ] Process and import lines
- [x] Roll tiles
