### ISSUE TITLE
North Bay Area Lines

### ISSUE THREAD

**Issue by ItoErika** [UW-Macrostrat/burwell-processing#129]
## Info
**Name:**
North Bay Area Lines

**Source URL:**
https://pubs.usgs.gov/mf/2000/2337/

**Comments:**
There only appear to be fault lines for this source. The ma-strc.e00 file did not have any line data. 

## Todo:

- [ ] Insert new source record
- [ ] Add data to database
- [ ] Process and add to homogenized tables
- [ ] Match
- [x] Process and import lines
- [ ] Roll tiles
