### ISSUE TITLE
Spain 1:1,00,000

### ISSUE THREAD

**Issue by jczaplew** [UW-Macrostrat/burwell-processing#131]
## Info
**Name:**
Mapa Geológico de la Península Ibérica, Baleares y Canarias a escala 1:1.000.000, edición 1995

**Source URL:**
http://info.igme.es/cartografiadigital/geologica/Geologicos1MMapa.aspx?Id=Geologico1000_(1994)

**Estimated scale:**
small

**Number of bedrock polygons:**
16,119

**Lithology field:**
lithology, lithofacies

**Time field:**
eon_era, subera, period, epoch, stage

**Stratigraphy name field:**

**Description field:**
description

**Comments field:**
domain

**Comments:**

1) The lines with tipo "contacto mechanico" were not assigned a new_type. I was unsure as to whether these lines might represent faults or shear zones. 

2) It looks like none of the points for this source would be useful so I did not push them. I still have them in the original downloads folder in case we want to revisit them later. 

3) Also maybe worth mentioning that Riphean, Buntsandstein-Muschelkalk, and Keuper time interval names were used in the source. I used looser time restraints to set early and late ids for these: 

Riphean: Neoproterozoic - Mesoproterozoic
Buntsandstein-Muschelkalk: Middle Triassic - Late Permian 
Keuper: Late Triassic - Middle Triassic

## Todo:

- [x] Download and process source
- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Match
- [x] Process and import lines
- [x] Roll tiles
