### ISSUE TITLE
Alameda County, CA

### ISSUE THREAD

**Issue by jczaplew** [UW-Macrostrat/burwell-processing#139]
## Info
**Name:**
Preliminary Geologic Map Emphasizing Bedrock Formations in Alameda County, California: A Digital Database

**Source URL:**
http://pubs.usgs.gov/of/1996/of96-252/

**Estimated scale:**
large

**Number of bedrock polygons:**
2,024

**Lithology field:**

**Time field:**
age

**Stratigraphy name field:**
name

**Description field:**
descriptions

**Comments field:**
assemblage

**Comments:**

1) Harmonized lines shapefile is titled "Lines". 

2) The unit sc was not in the pamphlet but based on other California sources, I figured it was silica-carbonate rocks. 

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [ ] Match
- [x] Process and import lines
- [x] Roll tiles
