### ISSUE TITLE
San Jose, CA

### ISSUE THREAD

**Issue by jczaplew** [UW-Macrostrat/burwell-processing#149]
## Info
**Name:**
Preliminary Geologic Map of the San Jose 30 X 60 Minute Quadrangle, California: A Digital Database

**Source URL:**
http://pubs.usgs.gov/of/1998/of98-795/

**Estimated scale:**
large

**Number of bedrock polygons:**
9,200

**Lithology field:**

**Time field:**
age

**Stratigraphy name field:**
name

**Description field:**
description

**Comments field:**
block (describes stuctural block or map area)

**Comments:**

1) There were no points of interest for this source (only faults).

2) There were no fold lines for this source. 

3) Unit fws (Ward Creek (?) terrane) did not have an age in the unit descriptions. I did not assign one in the attribute table. 

4) The unit Kgr had was described as being "Cretaceous or older". The unit is also described as having radiometric ages of 95-120 Ma. I assigned Jurassic as an early_id because it seemed the most reasonable. 

5) There are a few ptype entities that did not appear in the unit descriptions pdf. (gb, sz, gi, sill, bi). Based on the map and common sense, I assigned the description "sill" to the sill ptype polygons. Also based on the map, I assigned "shear zone" as a description to the sz ptype polygons. I am not sure what gb, gi, or bi are supposed to be, but each is only represented by a single, very small polygon. 

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Process and import lines
- [x] Match
- [ ] Roll tiles
