### ISSUE TITLE
Greenwood, Alabama - Fixed

### ISSUE THREAD

**Issue by ItoErika** [UW-Macrostrat/burwell-processing#17]
## Info

**Name:** Greenwood, Alabama 

**Source URL:** http://www.ogb.state.al.us/gsa/QS_results.aspx?PubID=QS44

**Estimated scale:** Large

**Lithology field:** Description

**Time field:** Age

**Stratigraphy name field:** Unit

**Description field:** 

**Comments field:**

**Comments:**
## Todo:
- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [ ] Match
- [ ] Roll tiles
- [ ] Process and import lines
