### ISSUE TITLE
Hawaii - not truncated

### ISSUE THREAD

**Issue by josiesajbel** [UW-Macrostrat/burwell-processing#2]
## Info

**Name:** Hawaii 

**Source URL:** http://catalog.data.gov/dataset/geologic-map-of-the-state-of-hawaii

**Estimated scale:** Medium

**Lithology field:** LITHOLOGY

**Time field:** age_code3_

**Stratigraphy name field:** NAME

**Description field:** ROCK_TYPE, VOLC_STAGE, COMPOSITION

**Comments field:** 

**Comments:** 
## Todo:
- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Match
- [x] Roll tiles
- [ ] Import lines
