### ISSUE TITLE
Venezuela

### ISSUE THREAD

**Issue by cambro** [UW-Macrostrat/burwell-processing#217]
## Info
**Name:**

**Source URL:**
https://pubs.usgs.gov/ds/2006/199/

**Estimated scale:**
medium

**Number of bedrock polygons:**
6,572

**Lithology field:**
lithology

**Time field:**
age

**Stratigraphy name field:**
name

**Description field:**

**Comments field:**

**Comments:**

1) The final lines shapefile is titled "Lines". 

2) I left the original strat name and lithology columns in the geology table ("unit_name" and "lith"). I altered many of these to updated columns ("name" and "lithology") because many units had redundant data between the columns. 

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Process and import lines
- [ ] Process and import points
- [ ] Match
- [ ] Roll tiles
