### ISSUE TITLE
Lake Tahoe

### ISSUE THREAD

**Issue by jczaplew** [UW-Macrostrat/burwell-processing#220]
## Info
**Name:**
GEOLOGIC MAP OF THE LAKE TAHOE BASIN CALIFORNIA AND NEVADA

**Source URL:**
GIS Data: ftp://ftp.consrv.ca.gov/pub/dmg/rgmp/Published_GIS_Data/RGM_004_TahoeBasin_100k_v1/RGM_004_TahoeBasin_100k_v1.zip
Descriptions: ftp://ftp.consrv.ca.gov/pub/dmg/pubs/rgm/RGM_004/RGM4_Lake_Tahoe_2005_Pamphlet.pdf

Map & pamphlet available-->
http://www.quake.ca.gov/gmaps/rgm/tahoe/tahoe.html

**Estimated scale:**
Large

**Number of bedrock polygons:**

**Lithology field:**
name
**Time field:**
age
**Stratigraphy name field:**
strat_name
**Description field:**
description
**Comments field:**
reference
**Comments:**

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Process and import lines
- [x] Process and import points
- [ ] Match
- [ ] Roll tiles
