### ISSUE TITLE
Long Beach, CA

### ISSUE THREAD

**Issue by jczaplew** [UW-Macrostrat/burwell-processing#225]
## Info
**Name:**
Geologic Map of the Long Beach 30’ x 60’ Quadrangle, California

**Source URL:**
http://www.conservation.ca.gov/cgs/rghm/rgm/Pages/preliminary_geologic_maps.aspx
Pamphlet: 
ftp://ftp.consrv.ca.gov/pub/dmg/rgmp/Prelim_geo_pdf/Long_Beach_100k_v2.0_Pamphlet.pdf

PDF Map: ftp://ftp.consrv.ca.gov/pub/dmg/rgmp/Prelim_geo_pdf/Long_Beach_100k_v2.0_Map.pdf

GIS Data: https://doc.app.box.com/s/q80388ibgoa3yy0n8m9n22cfoe7l1u2t

**Estimated scale:**
large

**Number of bedrock polygons:**
2,274

**Lithology field:**

**Time field:**
age

**Stratigraphy name field:**
name

**Description field:**
description

**Comments field:**

**Comments:**
I emailed the CA survey and Carlos Gutierrez (Carlos.Gutierrez@conservation.ca.gov) emailed me the data link

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Process and import lines
- [x] Process and import points
- [ ] Match
- [ ] Roll tiles
