### ISSUE TITLE
Wood County, WI

### ISSUE THREAD

**Issue by jczaplew** [UW-Macrostrat/burwell-processing#254]
**Name:**
Bedrock Geology of Wood County, Wisconsin

**Source URL:**
http://wgnhs.uwex.edu/pubs/000304/

**Estimated scale:**
large

**Number of bedrock polygons:**
222

**Lithology field:**
N/A

**Time field:**
`age`

**Stratigraphy name field:**
`strat_name`

**Description field:**
`descrip`

**Comments field:**
N/A

**Comments:**
Polygons - `sources.wi_wood`
Lines - `sources.wi_wood_lines`
Points - `sources.wi_wood_points`

Some points contain strike/dip info, others contain things like the location of outcrops and quarries.

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Process and import lines
- [x] Process and import points
- [ ] Match
- [ ] Roll tiles
