### ISSUE TITLE
Chisos Mountains, TX

### ISSUE THREAD

**Issue by cambro** [UW-Macrostrat/burwell-processing#279]
**Name:**
Geologic Map of the Chisos Mountains, Big Bend National Park, Texas

**Source URL:**
https://pubs.usgs.gov/sim/3140/

**Estimated scale:**
large

**Folder name:**
tx_chisos

**Dataset names:**

**Number of bedrock polygons:**
3081

**Comments:**
Manually copied PDF descriptions, some ligature and line break errors still possible.

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Process and import lines
- [x] Process and import points
- [x] Match
- [ ] Roll tiles
