### ISSUE TITLE
Tooele, UT

### ISSUE THREAD

**Issue by jczaplew** [UW-Macrostrat/burwell-processing#286]
**Name:**

**Source URL:**
GIS Data: https://ugspub.nr.utah.gov/publications/GIS_maps/tooele3060_ofr-669.zip
PDF: https://ugspub.nr.utah.gov/publications/open_file_reports/ofr-669.pdf
Index page: http://geology.utah.gov/map-pub/maps/gis/#tab-id-1

**Estimated scale:**
large

**Folder name:**
ut_tooele

**Dataset names:**

**Number of bedrock polygons:**

**Lithology field:**

**Time field:**

**Stratigraphy name field:**

**Description field:**

**Comments field:**

**Comments:**

## Todo:

- [x] Insert new source record
- [ ] Add data to database
- [ ] Process and add to homogenized tables
- [ ] Process and import lines
- [ ] Process and import points
- [ ] Match
- [ ] Roll tiles

**Comment by cvavrus** [comment]
Suggested inserts:
```
INSERT INTO maps.large (orig_id,source_id,name,age,lith,descrip,comments,strat_name,t_interval,b_interval,geom) 
SELECT gid,263,unitname,age_strat,compositio,descrip,genesis,strat_name,late_id,early_id,ST_MakeValid(geom) FROM sources.ut_tooele where geom is not null;
```
```
INSERT INTO lines.large (orig_id,source_id,descrip,name,new_type,geom) 
SELECT gid, 263,feature,featurenam,new_type,ST_MakeValid(geom) FROM sources.ut_tooele_lines where new_type is not null and geom is not null;
```
```
INSERT INTO points.points (orig_id,source_id,strike,dip,dip_dir,point_type,comments,geom) 
SELECT gid, 263,strike,dipangle,dipdirecti,point_type,feature,ST_MakeValid(geom) FROM sources.ut_tooele_points where point_type is not null and geom is not null;
```
Note that the values for some of the strike, dipangle, dipdirecti seem incorrect.

**Comment by cambro** [comment]
source_id 263
https://dev.macrostrat.org/burwell#10/40.74995/-112.50079
