### ISSUE TITLE
Hot Springs National Park, Arkansas - Fixed

### ISSUE THREAD

**Issue by ItoErika** [UW-Macrostrat/burwell-processing#30]
## Info

**Name:** Hot Springs National Park, Arkansas

**Source URL:** http://catalog.data.gov/dataset/unpublished-interim-digital-geologic-map-of-hot-springs-national-park-and-vicinity-arkansa-2011

**Estimated scale:** medium?

**Number of bedrock polygons:** 178

**Lithology field:**description

**Time field:** age

**Stratigraphy name field:** GLG NAME

**Description field:** Mj lith

**Comments field:**

**Comments:**
## Todo:
- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Match
- [x] Roll tiles
- [x] Process and import lines
- [x] Process and import points
