### ISSUE TITLE
Ware, BC

### ISSUE THREAD

**Issue by cvavrus** [UW-Macrostrat/burwell-processing#358]
**Name:**
Fallas, K.M. and Okulitch, A.V., 2015. GIS dataset of geology, Ware (94F), British Columbia; Geological Survey of Canada, Open File 5339, 1 .zip file. doi:10.4095/295723

**Source URL:**
https://doi.org/10.4095/295723

**Estimated scale:**
large

**Folder name:**
bc_ware

**Dataset names:**
bc_ware
bc_ware_lines

**Number of bedrock polygons:**
621

**Lithology field:**
lith_list

**Time field:**
use_age

**Stratigraphy name field:**
strat_name

**Description field:**
descrip

**Comments field:**

**Comments:**
Drift map units are located in a different .shp file

## Todo:

- [x] Insert new source record
- [ ] Add data to database
- [ ] Process and add to homogenized tables
- [ ] Process and import lines
- [ ] Process and import points
- [ ] Match
- [ ] Roll tiles

**Comment by cvavrus** [comment]
Suggested inserts:
```
INSERT INTO maps.large (orig_id,source_id,name,age,lith,descrip,comments,strat_name,t_interval,b_interval,geom) 
SELECT gid,231,map_unit,use_age,lith_list,descrip,genesis,strat_name,late_id,early_id,ST_MakeValid(geom) FROM sources.bc_ware WHERE geom IS NOT NULL;
```
```
INSERT INTO lines.large (orig_id,source_id,name,descrip,new_type,geom) 
SELECT gid,231,name,concat_ws('; ',subfeature,concat('orientation ',attitude),concat('location ',confidence),concat('age ',concat(max_age,'- ',min_age))),new_type,ST_MakeValid(geom) FROM sources.bc_ware_lines where new_type is not null and geom is not null;
```
points are fossils only

**Comment by cambro** [comment]
source_id 231
https://dev.macrostrat.org/burwell#10/57.5/-125
