### ISSUE TITLE
Campbell Lake, NWT

### ISSUE THREAD

**Issue by cvavrus** [UW-Macrostrat/burwell-processing#363]
**Name:**
Cecile, M.P., Lane, L.S., Dyke, L.D., and Norris, D.K., 2017. Bedrock geology, Campbell Lake, Northwest Territories; Geological Survey of Canada, Canadian Geoscience Map 179 (preliminary), scale 1:50 000. doi:10.4095/298807

**Source URL:**
https://doi.org/10.4095/298807

**Estimated scale:**
large

**Folder name:**
nwt_campbell

**Dataset names:**
nwt_campbell
nwt_campbell_lines
nwt_campbell_points

**Number of bedrock polygons:**
26

**Lithology field:**

**Time field:**
use_age

**Stratigraphy name field:**
strat_name

**Description field:**
descrip

**Comments field:**

**Comments:**

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [ ] Process and add to homogenized tables
- [ ] Process and import lines
- [ ] Process and import points
- [ ] Match
- [ ] Roll tiles

**Comment by cvavrus** [comment]
Suggested inserts:
```
INSERT INTO maps.large (orig_id,source_id,name,age,descrip,strat_name,t_interval,b_interval,geom) 
SELECT gid,230,map_unit,use_age,descrip,strat_name,late_id,early_id,ST_MakeValid(ST_Force2D(geom)) FROM sources.nwt_campbell where geom is not null;
```
```
INSERT INTO lines.large (orig_id,source_id,descrip,new_type,geom) 
SELECT gid,230,descrip,new_type,ST_MakeValid(ST_Force2D(geom)) FROM sources.nwt_campbell_lines where new_type is not null and geom is not null;
```
```
INSERT INTO points.points (orig_id,source_id,strike,dip,dip_dir,point_type,comments,geom) 
SELECT gid,230,strike,dip,dip_dir,point_type,remarks,ST_MakeValid(ST_Force2D(geom)) FROM sources.nwt_campbell_points where point_type is not null and geom is not null;
```

**Comment by cambro** [comment]
needed to force 2d on insert into standard tables.
source_id 230
https://dev.macrostrat.org/burwell#10/68.125/-133.5
