### ISSUE TITLE
Rae Craton and Queen Maud Block, NU

### ISSUE THREAD

**Issue by cvavrus** [UW-Macrostrat/burwell-processing#372]
**Name:**
Skulski, T., Paul, D., Sandeman, H., Berman, R.G., Chorlton, L., Pehrsson, S.J., Rainbird, R.H., Davis, W.J., and Sanborn-Barrie, M., 2018. Bedrock geology, central Rae Craton and eastern Queen Maud Block, western Churchill Province, Nunavut; Geological Survey of Canada, Canadian Geoscience Map 307, scale 1:550 000. https://doi.org/10.4095/308348

**Source URL:**
https://doi.org/10.4095/308348

**Estimated scale:**
medium

**Folder name:**
nu_rae

**Dataset names:**
nu_rae
nu_rae_lines

**Number of bedrock polygons:**
3548

**Lithology field:**

**Time field:**
use_age

**Stratigraphy name field:**
strat_name

**Description field:**
descrip

**Comments field:**

**Comments:**
'Unmapped area' polygons on this map
Shear zone polygons in separate .shp file
Geochronology data also available in separate .shp files

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [ ] Process and add to homogenized tables
- [ ] Process and import lines
- [ ] Process and import points
- [ ] Match
- [ ] Roll tiles

**Comment by cvavrus** [comment]
Suggested inserts:
```
INSERT INTO maps.medium (orig_id,source_id,name,age,descrip,strat_name,comments,t_interval,b_interval,geom) 
SELECT gid,248,group_,use_age,descrip,strat_name,type,late_id,early_id,ST_MakeValid(geom) FROM sources.nu_rae where geom is not null;
```
```
INSERT INTO lines.medium (orig_id,source_id,descrip,new_type,geom) 
SELECT gid,248,descrip,new_type,ST_MakeValid(geom) FROM sources.nu_rae_lines where new_type is not null and geom is not null;
```

**Comment by cambro** [comment]
@cvavrus if there are any more maps at this scale be sure to grab them!

**Comment by cambro** [comment]
source_id 248

the group_ field was not the best unit name... had to add a new column and populate it with several different fields.
https://dev.macrostrat.org/burwell#7/66.999985/-90.999995
