### ISSUE TITLE
Bedrock Lithology in Allen County, Indiana

### ISSUE THREAD

**Issue by ericjohannes** [UW-Macrostrat/burwell-processing#401]
**Name:**

BEDROCK_GEOLOGY_IGS_ALLEN: Bedrock Lithology in Allen County, Indiana (Indiana Geological Survey, scale 1:63,360, Polygon Personal GeoDatabase Feature Class)

**Source URL:**

https://iu.box.com/s/rxks2hqt2uns6yzpg60u5pk9onm0j9lq

**Estimated scale:**

large

**Folder name:**

**Dataset names:**

AllenCounty_BedrockGeology.shp

**Number of bedrock polygons:**
31

**Lithology field:**

**Time field:**

System

**Stratigraphy name field:**

Stratigrap

**Description field:**

Unit_Desc

**Comments field:**

**Comments:**

Abstract: The polygon geodatabase feature class shows the bedrock geology in Allen County, Indiana. The data includes the geologic systems and the stratigraphic names of the bedrock units. The dominant bedrock types include limestone, dolomite, and shale. The ages range from Silurian to Upper Devonian. This was originally digitized from Plate 2 Map of Allen County, Indiana showing the topography and geology of the bedrock surface from Fleming, A. H., 1994, the hydrogeology of Allen County, Indiana - a geologic and ground-water atlas, Indiana Geological Survey Special Report 57, 111 p.

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [ ] Process and import lines
- [ ] Process and import points
- [x] Match
- [x] Roll tiles

**Comment by cambro** [comment]
source_id 260
https://dev.macrostrat.org/burwell/#11/41.0832/-85.0544
