### ISSUE TITLE
Preliminary Map Showing Bedrock Geology of the Mooresville West 7.5-Minute Quadrangle, Indiana

### ISSUE THREAD

**Issue by ericjohannes** [UW-Macrostrat/burwell-processing#446]
**Name:**

Rupp, R. F., McLaughlin, P. L., Bancroft, A.M., Hasenmueller, W. A., and Johnson, M.R., 2017, Preliminary Map Showing Bedrock Geology of the Mooresville West 7.5-Minute Quadrangle, Indiana: Indiana Geological Survey Open-File Study 17-03, scale 1:24,000

**Source URL:**

https://iu.box.com/s/sybsqbdzoipp95ief2jxzq1kf4dum9e6

**Estimated scale:**

large

**Folder name:**

**Dataset names:**

BedrockGeology_MooresvilleWest

**Number of bedrock polygons:**
9

**Lithology field:**

**Time field:**

Top_age, Bottom_age

**Stratigraphy name field:**

UnitName

**Description field:**

UnitDescri

**Comments field:**

**Comments:**

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [ ] Process and import lines
- [ ] Process and import points
- [x] Match
- [x] Roll tiles

**Comment by cambro** [comment]
https://igws.indiana.edu/Bedrock
source_id=289
no lines, no points

https://dev.macrostrat.org/burwell#10/39.56251/-86.4375
