### ISSUE TITLE
Bunda, New South Wales

### ISSUE THREAD

**Issue by cvavrus** [UW-Macrostrat/burwell-processing#458]
**Name:**
Mills, K.J. and Hicks, M.G. 2016. Bunda 1:100,000 Geological Sheet 7434. Second Edition. Geological Survey of New South Wales, Maitland.

**Source URL:**
https://search.geoscience.nsw.gov.au/product/16

**Estimated scale:**
large

**Folder name:**
nsw_bunda

**Dataset names:**
nsw_bunda
nsw_bunda_lines
nsw_bunda_points

**Number of bedrock polygons:**
713

**Lithology field:**

**Time field:**
use_age

**Stratigraphy name field:**
strat_name

**Description field:**
descrip

**Comments field:**

**Comments:**

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [ ] Process and add to homogenized tables
- [ ] Process and import lines
- [ ] Process and import points
- [ ] Match
- [ ] Roll tiles

**Comment by cvavrus** [comment]
Suggested inserts:
```
INSERT INTO maps.large (orig_id,source_id,name,age,descrip,comments,strat_name,t_interval,b_interval,geom) 
SELECT gid,274,mapunit,use_age,descrip,surface1,strat_name,late_id,early_id,ST_MakeValid(geom) FROM sources.nsw_bunda where geom is not null;

INSERT INTO lines.large (orig_id,source_id,descrip,name,new_type,geom) 
SELECT gid,274,codedescpt,strucname,new_type,ST_MakeValid(geom) FROM sources.nsw_bunda_lines where new_type is not null and geom is not null;

INSERT INTO points.points (orig_id,source_id,strike,dip,dip_dir,point_type,comments,geom) 
SELECT gid,274,strike,dip,azimuth,point_type,codedescpt,ST_MakeValid(geom) FROM sources.nsw_bunda_points where point_type is not null and geom is not null;
```

**Comment by cambro** [comment]
source_id 274
https://dev.macrostrat.org/burwell#10/-31.75/142.75
