### ISSUE TITLE
Bogan Gate, NSW

### ISSUE THREAD

**Issue by rleverett** [UW-Macrostrat/burwell-processing#518]
**Name:**
Sherwin L., Raymond O.L. and Wallace D.A., 2000, Bogan Gate 1:100 000 Geological Sheet 8431, 1st edition. Geological Survey of New South Wales, Sydney & Geoscience Australia, Canberra.
--

**Source URL:**
https://search.geoscience.nsw.gov.au/product/47

**Estimated scale:**
large

**Folder name:**
nsw_bogangate

**Dataset names:**
nsw_bogangate
nsw_bogangate_lines

**Number of bedrock polygons:**
763

**Lithology field:**

**Time field:**
age

**Stratigraphy name field:**
strat_name

**Description field:**
lith_desc

**Comments field:**

**Comments:**

## Todo:

- [ ] Insert new source record
- [x] Add data to database
- [ ] Process and add to homogenized tables
- [ ] Process and import lines
- [ ] Process and import points
- [ ] Match
- [ ] Roll tiles

**Comment by rleverett** [comment]
No points files

Suggested Inserts:
```
INSERT INTO maps.large (orig_id,source_id,name,age,descrip,strat_name,t_interval,b_interval,geom) 
SELECT gid,284,unitname,age,lith_desc,strat_name,late_id,early_id,ST_MakeValid(geom) FROM sources.nsw_bogangate where geom is not null;
```
```
INSERT INTO lines.large (orig_id,source_id,descrip,new_type,geom) 
SELECT gid,284,desc_,new_type,ST_MakeValid(geom) FROM sources.nsw_bogangate_lines where new_type is not null and geom is not null;
```

**Comment by cambro** [comment]
source_id 284
https://dev.macrostrat.org/burwell#10/-33.248455/147.751205
