### ISSUE TITLE
LissadellAustralia - not truncated

### ISSUE THREAD

**Issue by josiesajbel** [UW-Macrostrat/burwell-processing#6]
## Info

**Name:** LissadellAustralia

**Source URL:** http://www.ga.gov.au/metadata-gateway/metadata/record/gcat_a05f7892-b449-7506-e044-00144fdd4fa6/Geology+of+the+Lissadell

**Estimated scale:** Large

**Lithology field:** ROCKTYPE, LITH_DESC

**Time field:** ERA, PERIOD

**Stratigraphy name field:** UNITNAME

**Description field:** LITH_DESC

**Comments field:** SUPERGROUP, GROUP, SUBGROUP, FORMATION

**Comments:**
## Todo:
- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Match
- [x] Roll tiles
