### ISSUE TITLE
Nephi, Utah

### ISSUE THREAD

**Issue by ItoErika** [UW-Macrostrat/burwell-processing#92]
## Info

**Name:**
Nephi, Utah

**Source URL:**
http://geology.utah.gov/map-pub/maps/gis/#tab-id-1

**Estimated scale:**
large

**Number of bedrock polygons:**
2,041

**Lithology field:**
description

**Time field:**
age

**Stratigraphy name field:**
unitname

**Description field:**
description

**Comments field:**

**Comments:**

1) There was no metadata in the original zip folder from the source.

2) Strike and dips are shown on the map with line symbols rather than points. 
## Todo:
- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Match
- [ ] Process and import lines
- [ ] Roll tiles
