### ISSUE TITLE
DutchJohnUtah

### ISSUE THREAD

**Issue by josiesajbel** [UW-Macrostrat/burwell-processing#94]
## Info

**Name:** DutchJohnUtah

**Source URL:** http://geology.utah.gov/map-pub/maps/gis/#tab-id-1

**Estimated scale:** Large

**Number of bedrock polygons:** 3054

**Lithology field:** litho

**Time field:** age

**Stratigraphy name field:** unitname

**Description field:** litho

**Comments field:** notes

**Comments:** In the folder is a new table (newdutchjohnutah.sql.gz) with no truncated lithologies, also including early_id and late_id. Points and lines are included in the folder.
## Todo:
- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Match
- [ ] Process and import lines
- [ ] Roll tiles
