### ISSUE TITLE
Manti, Utah

### ISSUE THREAD

**Issue by ItoErika** [UW-Macrostrat/burwell-processing#95]
## Info

**Name:**
Manti, Utah

**Source URL:**
http://geology.utah.gov/map-pub/maps/gis/#tab-id-1

**Estimated scale:**
large

**Number of bedrock polygons:**
2,544

**Lithology field:**
description

**Time field:**
age

**Stratigraphy name field:**
unitname

**Description field:**
description

**Comments field:**

**Comments:**

1) The only metedata that came in the source zipfile was for the basemap that image. 

2) Ball and bar fault symbols are comprised of lines on the map.
## Todo:
- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Match
- [x] Process and import lines
- [ ] Roll tiles
